from random import choice


word1 = ["Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden","Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden",
         "Minden", "Minden", "Minden", "Minden", "Minden", "Minden"]


word2 = ["szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar"
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar",
         "szar", "szar", "szar", "szar", "szar", "szar", "szar", "szar"]


punctuation = [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".",
               ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."]


print(f"KOMBINATORIKUS VERS\n\n{choice(word1)} {choice(word2)}{choice(punctuation)}")


